
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.production
    image: ghcr.io/pcerezo/chacobache_api/backend:latest
    ports: 
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - EMAIL_CODE=${EMAIL_CODE}
      - EMAIL_DESTINO=${EMAIL_DESTINO}
      - EMAIL_USER=${EMAIL_USER}
    #links:
    #  - sqlnet
    volumes:
      - .:/home/app
