
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghcr.io/pcerezo/chacobache_api/backend:latest
    ports: 
      - "5000:5000"
    environment:
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
      - EMAIL_CODE=${EMAIL_CODE}
      - EMAIL_DESTINO=${EMAIL_DESTINO}
      - EMAIL_USER=${EMAIL_USER}
    links:
      - sqlnet
    volumes:
      - .:/home/app
  sqlnet:
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
